#!/usr/bin/python3
"""Script to find free lab machine."""
import argparse
import subprocess
import random
import json


# nov2022: lab machine regexp
# aug2023: temporarily remove edge, vertex & arc - for Summer 2023 lab overhaul
# sep2023: update to reflec lab 2023/2024 set-up
LABCOMPS = "^(gpu|ray)[0-9]{2}\.doc"
#LABCOMPS = "^(edge)[0-9]{2}\.doc"


# Arguments
parser = argparse.ArgumentParser(description="Tool to find a free lab machine.")
parser.add_argument(
    "-c",
    "--constraint",
     default='regexp( \"' + LABCOMPS + '\", Machine)',
     help="Constraint on which machines to select.",
)
ARGS = parser.parse_args()

# Get condor machine status
# We restrict to lab machines only
condor_status = subprocess.run(
    [
        "/usr/local/condor/release/bin/condor_status",
        "-long",
        "-attributes",
        "Machine,LoadAvg,State",
        "-json",
        "-constraint",
        ARGS.constraint,
    ],
    stdout=subprocess.PIPE,
    check=True,  # Raises exception if subprocess fails
)

# Collect machine information,
machines = json.loads(condor_status.stdout)

# Rule 1: Pick a random unclaimed machine with less than 0.1 load average
# We set less than 0.1 load average to avoid any other process such as root
# package updates from running in the background that Condor does not pick up
unclaimed = filter(lambda m: m["State"] == "Unclaimed" and m["LoadAvg"] < 0.1, machines)

# Rule 2: Pick a random Claimed machine, yield from Condor for interactive usage
# Interactive usage takes priority over Condor jobs
claimed = filter(lambda m: m["State"] == "Claimed", machines)

# Rule 3: Shared usage, all machines are used at the moment, we'll first pick machines
# that have half the cpu load, i.e. < 4.0 load average
low_usage = filter(lambda m: m["LoadAvg"] < 0.1, machines)

# Rule 4: All shared usage, all machines are used and have load average high,
# we have no option but to randomly pick one for the user
all_machines = machines

# Select a machine, yielding from rules in order
for ms in [unclaimed, claimed, low_usage, all_machines]:
    ms = list(ms)
    if ms:
        labm = random.choice(ms)["Machine"]
        # Check if we can reach the machine, is it running?
        pingt = subprocess.run(
            ["ping", "-c", "1", "-W", "1", labm],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
        if pingt.returncode == 0:
            print(labm)
            break
