debug:
    algo: ppo
    n_envs: 2
    n_steps: 64
    epoch: 1
    n_minibatch: 4
    mini_batch_size: 512
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

easy:
    algo: ppo
    n_envs: 64
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

easy-200:
    algo: ppo
    n_envs: 128
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

hard:
    algo: ppo
    n_envs: 128
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 4096
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

hard-500-impala:
    algo: ppo
    n_envs: 256 
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

hard-500-impalavq:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    commit_coef: 1.0
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalavq
    recurrent: False

hard-500-impalavqmha:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.00005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    x_entropy_coef: 0.
    commit_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalavqmha
    recurrent: False
    mha_layers: 2

hard-500-impalavqmha-rib:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.00005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    x_entropy_coef: 0.
    commit_coef: 0.0
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalavqmha
    recurrent: False
    mha_layers: 2

#hard-500-impalamha:
#    algo: ppo
#    n_envs: 256
#    n_steps: 256
#    epoch: 3
#    n_minibatch: 8
#    mini_batch_size: 8192
#    gamma: 0.999
#    lmbda: 0.95
#    learning_rate: 0.00005
#    grad_clip_norm: 0.5
#    eps_clip: 0.2
#    value_coef: 0.5
#    entropy_coef: 0.01
#    normalize_adv: True
#    normalize_rew: True
#    use_gae: True
#    architecture: impalavqmha
#    recurrent: False
#    mha_layers: 4
#    use_vq: False

hard-500-impalafsq:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.00005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalafsq
    recurrent: False

hard-500-impalafsqmha-sparse:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.02
    sparsity_coef: 0.001
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalafsqmha
    recurrent: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [10, 10]
    n_impala_blocks: 3


hard-500-impalafsqmha:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.02
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalafsqmha
    recurrent: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [10, 10]
    n_impala_blocks: 3


hard-500-impalafsqitn:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalafsqitn
    recurrent: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [9, 9, 9]
    n_impala_blocks: 3
    use_intention: True

hard-500-impalamha:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 32
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalamha
    recurrent: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [9, 9, 9]
    n_impala_blocks: 3

hard-500-impalaitn:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalaitn
    recurrent: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [9, 9, 9]
    n_impala_blocks: 3
    use_intention: True


hard-500-impalafsqmha-valuetest:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.00005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.75
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impalafsqmha
    recurrent: False

hard-500-vqmha:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    commit_coef: 1.0
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: vqmha
    recurrent: False
    num_hiddens: 128
    num_downsampling_layers: 4
    num_residual_layers: 2
    num_residual_hiddens: 32
    embedding_dim: 8
    num_embeddings: 128
    use_ema: True
    decay: .99
    epsilon: 1e-5
    num_heads: 8
    model_path: "logs/vqvae/coinrun/vqvae/..."

hard-500-mem:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

hard-rec:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: True

hard-local-dev:
    algo: ppo
    n_envs: 16
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False

hard-local-dev-rec:
    algo: ppo
    n_envs: 16
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: True

A100:
    algo: ppo
    n_envs: 512
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 32768 # 32768  # this is just a maximum
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005 # should make larger?
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False


A100-large:  # for larger model (16x params)
    algo: ppo
    n_envs: 512
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 2048  # vary this param to adjust for memory
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005 # scale by 1 / sqrt(channel_scale)
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False


boxworld-impala:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False
    grid_size: 12
    goal_length: 5
    num_distractor: 3
    distractor_length: 3
    grid_size_v: 12
    goal_length_v: 5
    num_distractor_v: 3
    distractor_length_v: 3

boxworld-ribmha:
    algo: ppo
    n_envs: 32
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribmha
    recurrent: False
    max_steps: 1000
    grid_size: 12
    goal_length: 4
    num_distractor: 2
    distractor_length: 2
    grid_size_v: 12
    goal_length_v: 5
    num_distractor_v: 3
    distractor_length_v: 3

boxworld-ribfsqmha-easy:
    algo: ppo
    n_envs: 48
    n_steps: 64
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.001
    normalize_adv: True
    normalize_rew: False
    use_gae: True
    architecture: ribfsqmha
    recurrent: False
    max_steps: 1000
    grid_size: 6
    goal_length: 2
    num_distractor: 1
    distractor_length: 1
    grid_size_v: 6
    goal_length_v: 2
    num_distractor_v: 1
    distractor_length_v: 1
    use_vq: False
    entropy_scaling: time_based
    mha_layers: 2
    pool_direction: dim_wise
    levels: [10, 10]

boxworld-ribfsqmha:
    algo: ppo
    n_envs: 1024
    n_steps: 64
    epoch: 3
    n_minibatch: 32
    mini_batch_size: 2048
    gamma: 0.95
    lmbda: 0.95
    learning_rate: 0.0025
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.001
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribfsqmha
    recurrent: False
    max_steps: 1000
    grid_size: 12
    goal_length: 4
    num_distractor: 2
    distractor_length: 2
    grid_size_v: 12
    goal_length_v: 5
    num_distractor_v: 3
    distractor_length_v: 3
    use_vq: False
    mha_layers: 2
    pool_direction: dim_wise
    levels: [10, 10]




boxworld-ribmha-easy:
    algo: ppo
    n_envs: 48
    n_steps: 64
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.002
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribmha
    recurrent: False
    max_steps: 1000
    grid_size: 6
    goal_length: 2
    num_distractor: 1
    distractor_length: 1
    grid_size_v: 6
    goal_length_v: 2
    num_distractor_v: 1
    distractor_length_v: 1
    use_vq: False
    entropy_scaling: reward_based

boxworld-ribvqmha-easy:
    algo: ppo
    n_envs: 8192
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribmha
    recurrent: False
    max_steps: 1000
    grid_size: 6
    goal_length: 2
    num_distractor: 1
    distractor_length: 1
    grid_size_v: 6
    goal_length_v: 3
    num_distractor_v: 1
    distractor_length_v: 2
    use_vq: False

boxworld-ribmha-easy-100-steps:
    algo: ppo
    n_envs: 32
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribmha
    recurrent: False
    max_steps: 100
    grid_size: 6
    goal_length: 2
    num_distractor: 1
    distractor_length: 1
    grid_size_v: 6
    goal_length_v: 3
    num_distractor_v: 1
    distractor_length_v: 2


boxworld-ribmha-easy-100-steps-large-batch:
    algo: ppo
    n_envs: 1024
    n_steps: 256
    epoch: 3
    n_minibatch: 8
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.005
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: ribmha
    recurrent: False
    max_steps: 100
    grid_size: 6
    goal_length: 2
    num_distractor: 1
    distractor_length: 1
    grid_size_v: 6
    goal_length_v: 3
    num_distractor_v: 1
    distractor_length_v: 2
    
vq-vae:
    num_hiddens: 128
    num_downsampling_layers: 4
    num_residual_layers: 2
    num_residual_hiddens: 32
    embedding_dim: 8
    num_embeddings: 128
    use_ema: True
    decay: .99
    epsilon: 0.00001

cartpole:
    algo: ppo
    n_envs: 256
    n_steps: 256
    epoch: 3
    n_minibatch: 16
    mini_batch_size: 8192
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.02
    normalize_adv: True
    normalize_rew: False
    use_gae: True
    architecture: mlpmodel
    recurrent: False
    depth: 4
    latent_size: 64
    mid_weight: 256
